In [ ]:
from tensorflow import keras
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [ ]:
tf.config.experimental.list_physical_devices()

In [ ]:
(X_train, y_train), (X_test, y_test) = keras.datasets.cifar10.load_data()

In [4]:
X_train.shape, y_train.shape

((50000, 32, 32, 3), (50000, 1))

In [5]:
X_test.shape, y_test.shape

((10000, 32, 32, 3), (10000, 1))

In [6]:
np.unique(X_test)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [7]:
np.unique(y_test, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8),
 array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000],
       dtype=int64))

0	airplane,
1	automobile,
2	bird,
3	cat,
4	deer,
5	dog,
6	frog,
7	horse,
8	ship,
9	truck 

In [8]:
classes = ["airplane","automobile","bird","cat","deer","dog","frog","horse","ship","truck"]

In [9]:
for i in range(len(y_test)):
    print(y_test[i][0])
    print(classes[y_test[i][0]])

3
cat
8
ship
8
ship
0
airplane
6
frog
6
frog
1
automobile
6
frog
3
cat
1
automobile
0
airplane
9
truck
5
dog
7
horse
9
truck
8
ship
5
dog
7
horse
8
ship
6
frog
7
horse
0
airplane
4
deer
9
truck
5
dog
2
bird
4
deer
0
airplane
9
truck
6
frog
6
frog
5
dog
4
deer
5
dog
9
truck
2
bird
4
deer
1
automobile
9
truck
5
dog
4
deer
6
frog
5
dog
6
frog
0
airplane
9
truck
3
cat
9
truck
7
horse
6
frog
9
truck
8
ship
0
airplane
3
cat
8
ship
8
ship
7
horse
7
horse
4
deer
6
frog
7
horse
3
cat
6
frog
3
cat
6
frog
2
bird
1
automobile
2
bird
3
cat
7
horse
2
bird
6
frog
8
ship
8
ship
0
airplane
2
bird
9
truck
3
cat
3
cat
8
ship
8
ship
1
automobile
1
automobile
7
horse
2
bird
5
dog
2
bird
7
horse
8
ship
9
truck
0
airplane
3
cat
8
ship
6
frog
4
deer
6
frog
6
frog
0
airplane
0
airplane
7
horse
4
deer
5
dog
6
frog
3
cat
1
automobile
1
automobile
3
cat
6
frog
8
ship
7
horse
4
deer
0
airplane
6
frog
2
bird
1
automobile
3
cat
0
airplane
4
deer
2
bird
7
horse
8
ship
3
cat
1
automobile
2
bird
8
ship
0
airplane
8
shi

In [1]:
for i in range(10):
    plt.figure(figsize=(25,25))
    plt.imshow(X_test[i])
    plt.title('{} - {}'.format(y_test[i][0], classes[y_test[i][0]]))

NameError: name 'plt' is not defined

In [11]:
X_train_scaled = X_train / 255
X_test_scaled = X_test /255

In [12]:
y_train_encoded = keras.utils.to_categorical(y_train, num_classes=10)
y_train_encoded

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [13]:
y_test_encoded = keras.utils.to_categorical(y_test, num_classes=10)
y_test_encoded

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)

In [14]:
model = keras.Sequential([
        keras.layers.Flatten(input_shape=(32,32,3)),
        keras.layers.Dense(1000,activation='relu'),
        keras.layers.Dense(100,activation='relu'),
        keras.layers.Dense(10,activation='sigmoid')])

model.compile(optimizer='adam',
             loss='categorical_crossentropy',
             metrics=['accuracy'])

model.fit(X_train_scaled, y_train_encoded, epochs=1)





1563/1563 [==============================] - 58s 36ms/step - loss: 1.9244 - accuracy: 0.3045


In [15]:
model.evaluate(X_test_scaled, y_test_encoded)

313/313 [==============================] - 4s 10ms/step - loss: 1.8321 - accuracy: 0.3439


[1.8321402072906494, 0.34389999508857727]

In [16]:
yp_test = model.predict(X_test_scaled)
yp_test.shape, yp_test

313/313 [==============================] - 2s 7ms/step


((10000, 10),
 array([[0.45232671, 0.24426295, 0.72041154, ..., 0.34307668, 0.4100077 ,
         0.23207101],
        [0.8662178 , 0.9414182 , 0.364993  , ..., 0.25456938, 0.97020006,
         0.95265853],
        [0.922263  , 0.92892617, 0.53370744, ..., 0.3201258 , 0.9800538 ,
         0.90602577],
        ...,
        [0.06433434, 0.05237788, 0.3537162 , ..., 0.28086373, 0.1274138 ,
         0.05501481],
        [0.16465926, 0.09335375, 0.64960206, ..., 0.37223595, 0.09826776,
         0.07450412],
        [0.4431347 , 0.07262666, 0.673047  , ..., 0.8427906 , 0.16950871,
         0.13140287]], dtype=float32))

In [17]:
indices = np.argmax(yp_test,axis=1)
indices.shape, indices

((10000,), array([2, 8, 8, ..., 5, 6, 7], dtype=int64))

In [18]:
indices.reshape(-1,1)

array([[2],
       [8],
       [8],
       ...,
       [5],
       [6],
       [7]], dtype=int64)

In [19]:
y_test

array([[3],
       [8],
       [8],
       ...,
       [5],
       [1],
       [7]], dtype=uint8)

In [20]:
def get_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(32,32,3)),
        keras.layers.Dense(1000,activation='relu'),
        keras.layers.Dense(100,activation='relu'),
        keras.layers.Dense(10,activation='sigmoid')])

    model.compile(optimizer='SGD',
                 loss='categorical_crossentropy',
                 metrics=['accuracy'])
    return model

In [21]:
%%timeit -n1 -r1 
with tf.device('/CPU:0'):
    cpu_model = get_model()
    #cpu_model.fit(X_train_scaled, y_train_encoded, epochs=10)

167 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
